version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: quaythuong_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: quaythuong123
      MYSQL_DATABASE: quay_thuong
      MYSQL_USER: quaythuong_user
      MYSQL_PASSWORD: quaythuong_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - quaythuong_network
    command: --default-authentication-plugin=mysql_native_password

  # Node.js Application
  app:
    build: .
    container_name: quaythuong_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=quaythuong_user
      - DB_PASSWORD=quaythuong_pass
      - DB_NAME=quay_thuong
      - PORT=3000
      # Cấu hình tối ưu cho sharp
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1
      - SHARP_FORCE_GLOBAL_LIBVIPS=false
      # Cấu hình memory limit cho xử lý ảnh
      - NODE_OPTIONS=--max-old-space-size=2048
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./public/uploads:/app/public/uploads
    networks:
      - quaythuong_network
    # Tăng memory limit và đợi MySQL khởi động
    mem_limit: 1g
    mem_reservation: 512m
    command: sh -c "sleep 30 && npm start"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:

networks:
  quaythuong_network:
    driver: bridge